### ISSUE TITLE
Use in a game engine?

### ISSUE THREAD

**Issue by fire** [Hopetech/libSoftFloat#1]
Hi, would it be recommended to use this in the godot game engine as a emulated fp64 fallback because the game engine uses opengl es 3?

https://github.com/godotengine/godot/issues/288

**Comment by Hopetech** [comment]
Hello @fire,

Sorry for the (very very) late reply.
So yes, you can use this library in you game engine but this will require a lot of work in your compiler and the result will be slow as we emulate fp64.
This lib was designed for Mesa and contains only the base operations.

The plan for the Mesa implementation is to tell the preprocessor that base functions are available. Later in the compilation process, we lower double precision floating point operations to base ones.
For example, the `min` operation can be lowered as `lt(x,y)?x:y`.

You can probably do something similar in your project.
But keep in mind that fp64 is not always the solution for precision issues.

I've got some updates in my local branch. If you're interested, I can push it.

**Comment by fire** [comment]
Godot decided to have their renderer become based on vulkan and as a fall back for mobiles / older computers gles 2  / webgl 1.0.

As far as I know vulkan supports fp64.
